### ISSUE TITLE
Cannot sync locally

### ISSUE THREAD

**Issue by mstekinalp** [gadget-inc/ggt#409]
### Error ID

8bff26ef-340f-4b4b-b093-98cb3db20bb1

### What happened?

I got 2 errors while trying to sync local files. 

1. When I select merge files I got the error below:

"GGT_CLI_UNEXPECTED_ERROR: An unexpected error occurred
Error: EISDIR: illegal operation on a directory, read"

I do have read and write access. I tried running the command with sudo but the the browser did not open to login. 

2. When I select reset local files, I got the error below: 

[RangeError: path should be a `path.relative()`d string, but got ".."
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
RangeError: path should be a `path.relative()`d string, but got ".." ] 

### What did you expect to happen?

I expected to sync files I guess. 

### Steps to reproduce

try to sync. 

### Anything else?

Running on Ubuntu 22.04

**Comment by scott-rc** [comment]
Hey @mstekinalp 👋 -- sorry for the bugs 😞

I just released v0.1.16 which includes https://github.com/gadget-inc/ggt/pull/414 that fixes the first issue.

You can install the latest version via:

```sh
npm install --global @gadgetinc/ggt
```

I'm not sure why the second issue is occurring. I'm hoping that the second issue is caused by the first and both are resolved.

If either issue persists after upgrading, please re-open this issue.

**Comment by mstekinalp** [comment]
@scott-rc Thanks. I appreciate the quick help. It seems the issue is resolved.
