### ISSUE TITLE
Gadget File Sync is completely broken

### ISSUE THREAD

**Issue by mwood23** [gadget-inc/ggt#869]
### Error ID

a3a1ea2b-9986-4a23-84c9-402466c4bb78

### What happened?

Every time I go to save it errors so I can't do any development.

### What did you expect to happen?

It needs to sync otherwise I can't work on my project.

**Comment by scott-rc** [comment]
I'm sorry `ggt sync` wasn't working for you 😞 

We've made a number of improvements to ggt since this issue was opened, in particular:
- https://github.com/gadget-inc/ggt/releases/tag/v0.4.0
- https://github.com/gadget-inc/ggt/releases/tag/v0.4.7

Please retry with the latest version and feel free to re-open this issue if your problems persist.
